modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/emberbocor/villagertradepeek/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/emberbocor/villagertradepeek"
authors="emberbocor"
description='''
Shows every trade a villager will unlock at future levels in the trading screen.
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
